#
# SPDX-FileCopyrightText: Copyright 2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
name: Build ML SDK (manifest + overrides)

on:
  workflow_call:
    inputs:
      overrides_json: { type: string, required: true }

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-24.04
            arch_tag: amd64
          - platform: ubuntu-24.04-arm
            arch_tag: arm64
      fail-fast: false

    container:
      image: ghcr.io/${{ github.repository_owner }}/ml-sdk-linux-${{ matrix.arch_tag }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root

    env:
      REPO_DIR: /home/mlsdkuser/src
      INSTALL_DIR: /home/mlsdkuser/install
      MANIFEST_URL: https://github.com/${{ github.repository_owner }}/ai-ml-sdk-manifest.git
      OVERRIDES: ${{ inputs.overrides_json }}

    steps:
      - name: update repositories and build
        run: /home/mlsdkuser/ci_build.sh